title: Blogfolio - Pierre Chaveroux [ t70n ]
description: Ideas, notes, and portfolio stories.
url: ""
baseurl: ""

theme: minima
plugins:
  - jekyll-seo-tag

header_pages:
  - engineering_course.md
  - international_mobility.md
  - sustainability_civic_engagement.md
  - career_development.md

show_excerpts: true
